require("plugin-config.bufferline")
require("plugin-config.cmp")
require("plugin-config.lsp")
require("plugin-config.lualine")
require("plugin-config.luatree")
require("plugin-config.telescope")
require("plugin-config.treesitter")
require("plugin-config.worktree")
