#!/usr/bin/env zsh
#using pandoc to convert vimwiki to pdf

pandoc "$1" \
    -f vimwiki \
    -t pdf \
    --include-in-header ~/.config/nvim/wiki2pdf/assets/inline_code.tex \
    --include-in-header ~/.config/nvim/wiki2pdf/assets/chapter_break.tex \
    -V linkcolor:blue \
    -V geometry:a4paper \
    -V geometry:margin=2cm \
    -V monofont="Hack Nerd Font Mono" \
    --highlight-style ~/.config/nvim/wiki2pdf/assets/my_style.theme \
    --pdf-engine=xelatex \
    --toc \
    -o "$2"
